defaults:
  - _self_
  - model: small
  - override hydra/launcher: submitit_slurm

ngpus: 1
tokens: 50257
add_vocab: ""

training:
  batch_size: 64  # 512
  accum: 1
  n_iters: 800000
  snapshot_freq: 40000
  log_freq: 50
  eval_freq: 500
  snapshot_freq_for_preemption: 40000
  weight: standard
  snapshot_sampling: True
  ema: 0.9999

data:
  train: openwebtext
  valid: wikitext103
  cache_dir: data

graph:
  type: absorb
  file: data
  report_all: False

noise:
  type: loglinear
  sigma_min: 1e-4
  sigma_max: 20

sampling:
  predictor: euler
  steps: 32
  noise_removal: True

eval:
  batch_size: 32
  perplexity: False
  perplexity_batch_size: 32

optim:
  weight_decay: 0
  optimizer: AdamW
  lr: 1e-4
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
  warmup: 2500
  grad_clip: 1.


hydra:
  run:
    dir: /data/locus/project_data/project_data2/chenwu2/creativity_results/${data.train}/${now:%Y.%m.%d}/${now:%H%M%S}